# -*- coding: utf-8 -*-
"""steven_sampling.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1y_Uni68wJXqxkm89jGX_d6cdSIhVmHPT
"""

import random
import numpy
from sklearn.feature_selection import SelectKBest

def prob(x,sum):
  return 1.0/((x/50 +1)*sum)

def Steven_sampling(N,M):
  sum = 0
  groupcount = 60
  for i in range(M+1):
    sum+=1/(i/50+1)
  groupprob =[]
  probsum = 0.0
  for i in range(1,M+1):
    probsum +=prob(i,sum)
    if i%groupcount ==0:
      v=probsum
      groupprob.append(v)
      probsum =0.0
  grouptime = []
  for i in range(len(groupprob)):
    grouptime.append(0)

  for i in range(N):
    pro = random.random()
    s = 0.0
    for j in range(len(groupprob)):
     s+=groupprob[j]
     if pro<s:
       grouptime[j]+=1
       break
  print(grouptime)
  res=[]
  m=0
  for i in range(len(grouptime)):
     k = numpy.random.randint(low = m, high = (m+60), size = grouptime[i])  
    #  print(k)
     m+=60
    # random_num = random.choice(test_list)

    # temp = SelectKBest  (grouptime[i],i)
     res.extend(k.tolist())
  return res
Steven_sampling(20,300)



